spring:
  datasource:
      generate-unique-name: false
      name: tacocloud
      url: jdbc:postgresql://localhost:5432/taco_cloud
      username: postgres
      password: 1111
      driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      hbm2ddl:
        auto: none